Feature/enable application live view by default
vmware-tanzu/application-accelerator-samples pull request #123
Opened 2022-11-10 08:39 UTC by vmware-jaret

2022-11-10 15:40 UTC, trisberg reviewed
Labels can't have boolean values, have to be a string like "true" or you will get an error when applying

```
error: unable to decode "tanzu-java-web-app/config/workload.yaml": json: cannot unmarshal bool into Go struct field ObjectMeta.metadata.labels of type string
```

We should also add the label to `spring-cloud-serverless/kubernetes/tap/workload.yaml`

2022-11-10 15:44 UTC, trisberg requested changes
See comment regarding using string value instead of boolean

2022-11-11 13:36 UTC, trisberg approved these changes

2022-11-11 13:36 UTC, merged

2022-11-14 03:49 UTC, ksankaranara-vmw commented
Thanks everyone!! The changes to the actuators in the conventions code is now in the bundle 1.4.0-build.1 which is part of registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.4.0-build.8.